apiVersion: v1
kind: Service
metadata:
  name: springboot-example-service
spec:
  selector:
    app: springboot-example
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
